language: go

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -v -coverprofile=.coverprofile .

after_success:
  - $GOPATH/bin/gover
  - $GOPATH/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci